### ISSUE TITLE
Internet Explorer 11 throws when freezing the options

### ISSUE THREAD

**Issue by travisbale** [autoNumeric/autoNumeric#585]
https://github.com/autoNumeric/autoNumeric/blob/04c4764712ef2518f31491306172b5ad9551d5fd/src/AutoNumericOptions.js#L840

The [valueToStrings.none](https://github.com/autoNumeric/autoNumeric/blob/04c4764712ef2518f31491306172b5ad9551d5fd/src/AutoNumericOptions.js#L781) property is null, which when passed as a parameter to Object.freeze(), is throwing an "argument is not an Object" error in Internet Explorer 11, since it does not support ES2015.

See [Object.freeze() notes](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/freeze#Notes) for more details.

**Comment by AlexandreBonneau** [comment]
Thanks for reporting that IE quirks @travisbale.

Could you please try `v4.2.15` which should fix that bug?

**Comment by travisbale** [comment]
Yep, `v4.2.15` is working as expected. Thanks for the quick turnaround.

![keanu](https://user-images.githubusercontent.com/5521373/40860575-7c02e3b6-65ab-11e8-943c-5108fa7bb643.gif)

**Comment by AlexandreBonneau** [comment]
;)

**Comment by hjpfreitas** [comment]
Hello,

I'm using the version 4.2.15 from [https://unpkg.com/autonumeric@4.2.15/dist/autoNumeric.js](url) and the issue still there. 

I going to continue using the old version 1.9.46.

Can anyone check that?

Thanks.

**Comment by AlexandreBonneau** [comment]
@hjpfreitas Since other users have reported `v4.2.15` fixed the problem, could please paste here the error message you are seeing?
Are you sure you are not using a cached version of the library?

**Comment by hjpfreitas** [comment]
Hi @AlexandreBonneau , 

The version i'm using are from the link i mentioned before.  https://unpkg.com/autonumeric@4.2.15/dist/autoNumeric.js

![image](https://user-images.githubusercontent.com/13150720/42499846-bc88eff8-8427-11e8-8fc6-7e7ce692ea2a.png)

The error is:

- Object.freeze:  argument is not an Object 
  AutoNumericOptions.js (840,21)

Thanks

**Comment by hjpfreitas** [comment]
Hi @AlexandreBonneau,

The only reason i see is that version in [https://unpkg.com/autonumeric@4.2.15/dist/autoNumeric.js](url) is not the last version compiled.

Thanks

**Comment by AlexandreBonneau** [comment]
@hjpfreitas since `4.2.15` fixed the problem for @travisbale, could you tell us more about the error message? When is it displayed? On load? On a particular case?

If that's on load, I wonder why @travisbale did not encounter it too.

**Comment by shrpne** [comment]
@AlexandreBonneau I'm facing this issue too. I'm using `vue-autonumeric` which installs as a dependency `autonumeric` 4.5.1.

core-js polyfill fixes it:
```
import 'core-js/modules/es6.object.freeze';
import VueAutonumeric from 'vue-autonumeric/src/components/VueAutonumeric';
```

**Comment by AlexandreBonneau** [comment]
This is a nice workaround, thanks for sharing @shrpne .
Indeed, AutoNumeric uses `Object.freeze()` and IE11 does not support that without a polyfill.

Let's make a note for #539 :)
